### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by johnuphoff** [lemond/bucky_s-radio#1]

**Comment by lemond** [comment]
Let's go over this. You mentioned an organization?

**Comment by johnuphoff** [comment]
Yes / our company LeMond (we sell bikes).

**Comment by johnuphoff** [comment]
Anyway / if you are interested please let me know and hopefully we can try to work something out!

**Comment by lemond** [comment]
I see. Would a name that details lemond racing cycles work for you? No
fuss?

**Comment by johnuphoff** [comment]
I already have github.com @lemondtech / just hoping to open source some e-commerce solutions that I'm building for LeMond and it would be nice to have the @lemond handle for npm and such.

**Comment by johnuphoff** [comment]
So what do you think?  Are you interested in helping us out?

**Comment by lemond** [comment]
Unfortunately I have a strong interest too. I hope I don't find myself
crushed by juggernaut you're piloting.
